#!/bin/bash
# This config file is both for bash and powershell.
# In bash, it is sourced. In powershell, we need to read the file and add $.

# NOTE: This is not in use yet

# Find Python and pip
PYTHON3=$(which python3)
PYTHON="$PYTHON3"
PIP3=$(which pip3)
PIP="$PIP3"
GIT=$(which git)

# - VAR: TEMP_PATH ("/root/.phakit"): Temporary dir for installation files 
# - VAR: DEST_PATH (/etc/phakit) Destination (for phakit files): /etc/phakit
# - VAR: LINK_PATH (/usr/local/bin): Link path for symlinks

# LINK_PATH: Set link path (for symlinks)
LINK_PATH="/usr/local/bin"

# DEST_PATH: Set the destination path
DEST_PATH="/etc/phakit"
DEST_VERSION_FILE="$DEST_PATH/VERSION"

# TEMP_PATH: Set the temporary path
TEMP_PATH="$HOME/.phakit"

# CONFIG_IMPORTED: Set to 1 if the config file is imported
CONFIG_IMPORTED=1