#!/bin/bash
# This config file is both for bash and powershell.
# In bash, it is sourced. In powershell, we need to read the file and add $.

# NOTE: This is not in use yet

# LINK_PATH: Set link path (for symlinks)
LINK_PATH="/usr/local/bin"

# DEST_PATH: Set the destination path
DEST_PATH="/etc/phakit"
DEST_VERSION_FILE="$DEST_PATH/VERSION"

# TEMP_PATH: Set the temporary path
TEMP_PATH="$HOME/.phakit"