#!/bin/bash

# Path to your python script
SCRIPT_PATH="phakit.py"
DEST_PATH="/etc/phakit"

# Make sure Python exists
if ! command -v python3 &> /dev/null; then
    echo "[ERROR] Python 3 is not installed."
    exit 1
fi

# Check if pip packages are installed
REQUIRED_PYTHON_PACKAGES=("subprocess" "argparse")
for package in "${PACKAGES[@]}"; do
    if ! python3 -c "import $package" &> /dev/null; then
        echo "[ERROR] $package is not installed. Run 'pip install $package'."
        exit 1
    fi
done

# Check if the script exists
if [ ! -f "$SCRIPT_PATH" ]; then
    echo "[WARNING] $SCRIPT_PATH does not exist in PATH. Running from $DEST_PATH..."
elif [ -f "$DEST_PATH/$SCRIPT_PATH" ]; then
    SCRIPT_PATH="$DEST_PATH/$SCRIPT_PATH"
else
    echo "[ERROR] $DEST_PATH does not exist. Exiting..."
    exit 1
fi

# Call the python script with all arguments passed to the bash script
python3 "$SCRIPT_PATH" "$@"