#!/bin/bash


# ──────────────────────────── SECTION: PRECHECKS ──────────────────────────── #
LOCAL_APP_PATH="/usr/local/bin"

if [ ! -d "$LOCAL_APP_PATH" ]; then
    echo "[ERROR] $LOCAL_APP_PATH does not exist. Exiting..."
    exit 1
fi
# ──────────────────────────── !SECTION /PRECHECKS ─────────────────────────── #




# ──────────────────────────────────────────────────────────────────────────── #
#                              SECTION: LOCAL INCLUDES                         #
# ──────────────────────────────────────────────────────────────────────────── #
INCLUDES_IMPORTED="0"
LOCAL_APP_PATH="/usr/local/bin"
LOCAL_INCLUDES_FILE="$LOCAL_APP_PATH/linux"

source "$LOCAL_INCLUDES"

if [ -z "$LOCAL_INCLUDES" ] || [ "$LOCAL_INCLUDES" -ne "1" ]; then
    echo "[ERROR] Could not import includes file ($LOCAL_INCLUDES_FILE). Exiting..."
    exit 100
else
    print "[OK] Functions file imported." "SUCCESS"
fi

# ────────────────────── !SECTION /LOCAL INCLUDES ──────────────────────────── #

# Make sure Python exists
if ! command -v "$PYTHON3" &> /dev/null; then
    echo "[ERROR] Python 3 is not installed."
    quit 101 "Python 3 is not installed."
fi

# REVIEW: Revies this conditional mess at some point...
# Check if the script exists
# in PATH
if [ -f "$LOCAL_SCRIPT_PATH" ]; then
    SCRIPT_BIN="$LOCAL_SCRIPT_PATH"
else
    echo "[WARNING] $LOCAL_SCRIPT_PATH does not exist in PATH. Running from $LOCAL_LINK_PATH..."
    # as symlink
    if [ -f "$LOCAL_LINK_PATH" ]; then
        SCRIPT_BIN="$LOCAL_LINK_PATH"
    else
        echo "[WARNING] Symlinks not found in $LOCAL_LINK_PATH. Running from $LOCAL_PATH..."
        # as destination
        if [ -f "$LOCAL_PATH/$LOCAL_SCRIPT_PATH" ]; then
            SCRIPT_BIN="$LOCAL_PATH"
        else
            echo "[ERROR] $LOCAL_PATH does not exist. Exiting..."
            exit 1
        fi
    fi
fi

echo "[OK] Found phakit, running from $SCRIPT_BIN..."

# Call the python script with all arguments passed to the bash script
python3 "$SCRIPT_BIN" "$@"