#!/bin/bash

# ──────────────────────────────────────────────────────────────────────────── #
#                                    CONFIG                                    #
# ──────────────────────────────────────────────────────────────────────────── #
CONFIG_IMPORTED="0"
if [ -f "config" ]; then
    source "config"
else
    print "No config file found. Fetching from GitHub..."
    source <(curl -s https://raw.githubusercontent.com/Darknetzz/phakit/main/config)
fi

if [ "$CONFIG_IMPORTED" -ne "1" ]; then
    echo "Could not import config file."
    exit 100
fi



# Make sure Python exists
if ! command -v python3 &> /dev/null; then
    echo "[ERROR] Python 3 is not installed."
    exit 1
fi

# Check if pip packages are installed
REQUIRED_PYTHON_PACKAGES=("subprocess" "argparse")
for package in "${PACKAGES[@]}"; do
    if ! python3 -c "import $package" &> /dev/null; then
        echo "[ERROR] $package is not installed. Run 'pip install $package'."
        exit 1
    fi
done

# REVIEW: Revies this conditional mess at some point...
# Check if the script exists
# in PATH
if [ -f "$SCRIPT_PATH" ]; then
    SCRIPT_BIN="$SCRIPT_PATH"
else
    echo "[WARNING] $SCRIPT_PATH does not exist in PATH. Running from $LINK_PATH..."
    # as symlink
    if [ -f "$LINK_PATH" ]; then
        SCRIPT_BIN="$LINK_PATH"
    else
        echo "[WARNING] Symlinks not found in $LINK_PATH. Running from $DEST_PATH..."
        # as destination
        if [ -f "$DEST_PATH/$SCRIPT_PATH" ]; then
            SCRIPT_BIN="$DEST_PATH"
        else
            echo "[ERROR] $DEST_PATH does not exist. Exiting..."
            exit 1
        fi
    fi
fi

echo "[OK] Found phakit, running from $SCRIPT_BIN..."

# Call the python script with all arguments passed to the bash script
python3 "$SCRIPT_BIN" "$@"